language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- flake8 bucket
- pytest -s tests
- bandit bucket
notifications:
  slack: cs-cofc:uCexVCL9fjtSpV4A6YcmrCpj
